
# Project Information
site_name: LBNL Science IT Docs
site_description: concierge information technology services for science
site_author: Shawfeng Dong
site_url: https://lbnl-science-it.github.io/docs/

# Repository
repo_name: GitHub/lbnl-science-it/docs-source
repo_url: https://github.com/lbnl-science-it/docs-source
edit_uri: blob/master/docs/

# Copyright
copyright: 'Copyright &copy; LBNL 2020 Science IT Consultants'

# Configuration
theme:
  name: material
  favicon: images/favicon.ico
  logo: images/7_BL_Vert_547_rgb.png
  
# Page tree
nav:
    - Home: index.md
    - "Consulting & Training": consult.md
    - "High-Performance Computing": hpc.md
    - "Data Management & Storage": data.md
    - "Science General Support": support.md
    - "Compute Resources": compute.md
    - "Storage Resources": storage.md
    - "Cloud Resources": cloud.md
    - Tutorials:
        - "SpaRC on Lawrencium": sparc_on_lawrencium.md
        - "SpaRC on GCP": sparc_on_gcp.md
        - "Container 101 on Lawrencium": container-101.md
        - "Lawrencium: Singularity container using AWS DL docker images": singularity_docker.md 
        - "AWS SageMaker: Text Classification Using Keras & TensorFlow": sagemaker_keras_text_classification.md
        - "AWS SageMaker: Reinforcement Learning": rl_mountain_car_coach_gymEnv.md 
        - "Lawrencium: Jupyter Notebook on a GPU node":
            - "TensorFlow 1.12": jupyter_gpu.md
            - "TensorFlow 2.0": jupyter_gpu_tensorflow_2.0.md
            - "TensorFlow 2.1": jupyter_gpu_tensorflow_2.1.md
            - "JupyterHub": jupyterhub_gpu.md
